### ISSUE TITLE
Escape sequences really difficult to see

### ISSUE THREAD

**Issue by Toasterbirb** [FrenzyExists/aquarium-vim#16] opened 2022-06-21 22:40 UTC
**Describe the bug**
Escape sequences like \t and \n for example are really difficult to see. They blend in with the background and are almost the same color

**To Reproduce**
1. Install the aquarium-vim plugin
2. Enable the colorscheme with
```
set termguicolors
colorscheme aquarium
let g:aquarium_style="dark"
```
3. Open a text file that has syntax highlighting (eg. .cpp)

**Expected behavior**
Escape sequences would be more distinguishable and have a bit more contrast against a dark background

**Screenshots**
![newline](https://user-images.githubusercontent.com/48382422/174908192-98e1261f-15ae-4dab-a2fa-a21f7fd11711.png)

**OS (The operating system you're using):**
 - Linux

**Neovim (Your neovim version)**
- NVIM v0.7.0

**Adittional context**
I also tried to change my st colorscheme to aquarium, but that didn't change anything. NeoVim probably gets its background color from the colorscheme and doesn't care what background color st wants.

**Comment by FrenzyExists** [comment] 2022-06-22 06:36
It took me a bit of a while, forgot that I had Tree sitter activated. with tree sitter you can get better linting btw. Anyway, the problem is that Special character has the same highlight as what was originally the color of a comment, I'll fix it right away :+1:

**Comment by FrenzyExists** [comment] 2022-06-22 06:43
![image](https://user-images.githubusercontent.com/47986470/174961198-b607e998-60a7-42a9-b35f-b7f3fb9d358d.png)

This is how it should look later, I'll close the issue as resolved, if you think there's a better color feel free to open a new issue

**Closed as completed by FrenzyExists** 2022-06-22 06:43 UTC
